// Public Zuvix SDK entrypoint. Re-export client namespaces, event helpers,
// transport, and stable SDK types from focused modules.
export {
  Agent,
  AgentsNamespace,
  ApprovalsNamespace,
  ArtifactsNamespace,
  EnvironmentsNamespace,
  ModelsNamespace,
  Zuvix,
  Run,
  RunsNamespace,
  Session,
  SessionsNamespace,
  TasksNamespace,
  ToolsNamespace,
  type ZuvixOptions,
} from "./client.js";
export { EventHub, isGatewayEvent } from "./event-hub.js";
export { normalizeGatewayEvent } from "./normalize.js";
export { GatewayClientTransport, isConnectableTransport } from "./transport.js";
export type {
  AgentRunParams,
  ApprovalMode,
  ArtifactQuery,
  ArtifactSummary,
  ArtifactsDownloadResult,
  ArtifactsGetResult,
  ArtifactsListResult,
  ConnectableZuvixTransport,
  EnvironmentSelection,
  EnvironmentSummary,
  EnvironmentsListResult,
  GatewayEvent,
  GatewayRequestOptions,
  JsonObject,
  ZuvixEvent,
  ZuvixEventType,
  ZuvixTransport,
  RunCreateParams,
  RunResult,
  RunStatus,
  RuntimeSelection,
  SDKError,
  SDKMessage,
  SessionCreateParams,
  SessionSendParams,
  SessionTarget,
  TaskStatus,
  TaskSummary,
  TasksCancelResult,
  TasksGetResult,
  TasksListParams,
  TasksListResult,
  ToolInvokeParams,
  ToolInvokeResult,
  WorkspaceSelection,
} from "./types.js";
